server:
  port: 8018
spring:
  application:
    name: product-client
ribbon:
  eureka:
    enable: true
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    #下面一定要写 true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:9999/eureka
feign:
  hystrix:
    enabled: true #在 feign 中开启 hystrix 熔断机制